#!/usr/bin/env python3

import shutil
import os
import subprocess
import sys
import time
import datetime
import argparse
import traceback
import pwd


# make /usr/share/cryptobot before importing it so it can create the sqlite db
try:
    os.makedirs('/usr/share/cryptobot')

    cur_uid = os.geteuid()
    cryptobot_uid = pwd.getpwnam('cryptobot').pw_uid

    if cur_uid not in [0, cryptobot_uid]:
        raise PermissionError('You must be root to run this script')
    elif cur_uid == 0:
        # leave root and get cryptobot privs
        os.setuid(cryptobot_uid)
        cur_uid = cryptobot_uid
except PermissionError as e:
    print('Permission denied. Are you root?')
    raise e
except FileExistsError:
    pass

try:
    import cryptobot
    from cryptobot import logger, database, config
    from cryptobot.analysis import format_seconds
    from cryptobot import notifier
except ModuleNotFoundError as e:
    print('Cannot import cryptobot module, is the bot installed properly?')
    raise e


def getStats() -> list:
    stats = list()
    product_id = config.get('bot.coin') + '-USD'

    c = database.database()

    # coin type
    stats += [('Product ID', product_id)]

    # TODO: more order related things, like # buy/sells, total trade volume, current market trend, etc

    # portfolio balance
    balance = cryptobot.analysis.txn.get_balance()
    stats += [('Portfolio balance', ' :: '.join(['%.4f %s' % (float(deets['balance']), coin) for coin, deets in balance.items()]))]

    # number of orders
    r = c.execute('SELECT COUNT(*) AS numb FROM `orders` WHERE `product_id`=?', (product_id,))
    row = r.fetchone()
    numb = 0
    if row:
        numb = int(row[0])
    stats += [('Total number of orders', numb)]

    # number of analysis jobs run
    r = c.execute('SELECT COUNT(*) AS numb FROM `movement_score_history` WHERE `product_id`=?', (product_id,))
    row = r.fetchone()
    numb = 0
    if row:
        numb = int(row[0])
    stats += [('Total number of analysis jobs run', numb)]

    # number of cached price history datapoints
    r = c.execute('SELECT COUNT(*) AS numb FROM `price_history` WHERE `product_id`=?', (product_id,))
    row = r.fetchone()
    numb = 0
    if row:
        numb = int(row[0])
    stats += [('Total number of price history datapoints', numb)]

    c.close()
    return stats


if __name__ == '__main__':
    try:
        cryptobot.analysis._update_harnesses()

        parser = argparse.ArgumentParser()
        subparsers = parser.add_subparsers(dest='subparser')

        parser_status = subparsers.add_parser('status')
        parser_orders = subparsers.add_parser('orders')
        parser_logs = subparsers.add_parser('log')

        parser_analyze_market = subparsers.add_parser('analyze-market')
        parser_check_price = subparsers.add_parser('check-price')

        parser_analyze_market.add_argument('-f', '--force', default=False, action='store_true')

        args = parser.parse_args()

        logger.debug('$ ' + ' '.join([("'%s'" % x if ' ' in x else x) for x in sys.argv]))
        if args.subparser == 'status':
            logger.info('Performing cryptobot status check...', show_ts=False)

            if not os.path.isfile('/usr/share/cryptobot/history.db'):
                logger.warning('The history database does not exist yet. Have you run an analysis yet?', show_ts=False)
                exit(0)

            # find the last_movement_score from the database
            c = database.database()
            r = c.execute('SELECT datetime(`ts`, \'localtime\'), `score` FROM `movement_score_history` WHERE `product_id`=? ORDER BY id DESC LIMIT 1', (config.get('bot.coin') + '-USD',))
            row = r.fetchone()
            c.close()

            # if there was result (i.e. this is not the first run)
            if row:
                ts, last_movement_score = row
                ts = datetime.datetime.strptime(ts, '%Y-%m-%d %H:%M:%S').timestamp()
                time_since_last_run = time.time() - ts

                time_buffer = 60 * 5 # how many seconds off is acceptable
                analysis_runs_every = 60 * 60 # how many seconds between each run. DO NOT CHANGE THIS!

                # ensure the last movement score is valid
                if time_since_last_run < analysis_runs_every - time_buffer:
                    # nope! it's already run, so we don't need to / shouldn't run it again
                    logger.info('Analysis ran %s ago which is within the past hour (ts=%d, last_score=%.6f).' % (format_seconds(time_since_last_run), ts, last_movement_score), show_ts=False)
                    logger.debug('The analysis job should run again in %s, assuming all is well.' % (format_seconds(analysis_runs_every - time_since_last_run)), show_ts=False)
                elif time_since_last_run > (2 * analysis_runs_every) + time_buffer:
                    # nope! the change score is too old
                    # otherwise we could misinterpret the movement change score
                    logger.warning('Analysis ran %s ago which is not run last hour.' % format_seconds(time_since_last_run), show_ts=False)
                else:
                    logger.info('Analysis ran %s ago which is not within the last hour, but the score is not stale (cur_ts=%d, ts=%d, last_score=%.6f).' % (format_seconds(time_since_last_run), time.time(), ts, last_movement_score), show_ts=False)
            else:
                logger.warning('Analysis has never been performed; history.db is empty.', show_ts=False)
                exit()

            logger.info('-'*80, show_ts=False)
            stats = getStats()
            logger.info('[ Statistics ]', show_ts=False)
            for stat in stats:
                name, numb = stat
                logger.info('... %s: %s' % (name, str(numb)), show_ts=False)

        elif args.subparser == 'orders':
            msg = ''
            now = datetime.datetime.now()

            coin = config.get('bot.coin', 'coin')
            product_id = f'{coin}-USD'

            COLOR_BLUE = '\033[34m'
            COLOR_BLUE_BOLD = '\033[1;34m'
            COLOR_RED = '\033[31m'
            COLOR_RED_BOLD = '\033[1;31m'
            COLOR_GREEN = '\033[32m'
            COLOR_GREEN_BOLD = '\033[1;32m'
            COLOR_RESET = '\033[0m'

            c = database.database()
            r = c.execute('SELECT * FROM `orders` WHERE `product_id`=?', (product_id,))
            while (row := r.fetchone()):
                # NOTE: Here are some example `row`s:
                #   (None, datetime.datetime(2021, 2, 1, 0, 44, 29), 'BTC-USD', 'b8dce87f-0b32-44c7-afdd-7be800335e84', 'sell', 0.0010722, 0.0)
                #   (None, datetime.datetime(2021, 2, 1, 1, 44, 29), 'BTC-USD', 'dc511b9f-7044-4856-8a1b-a2536e5ab512', 'buy', 0.0, 67.68)
                _, ts, pid, oid, action, size, funds = row

                unixts = ts.timestamp()
                coin_price = cryptobot.analysis.history.get_historic_price(unixts, product_id_override=pid)
                portfolio = cryptobot.txn.coinbase.get_historic_balance(unixts)
                format_usd = lambda n: '${:,.2f}'.format(n)

                msg += f'{COLOR_BLUE}|-- {COLOR_RESET}{str(ts)}  {COLOR_BLUE_BOLD}{pid}{COLOR_RESET}  '
                msg += (COLOR_RED_BOLD if action == 'sell' else COLOR_GREEN_BOLD) + action.upper().ljust(4) + ' '

                if action == 'sell':
                    msg += COLOR_RED + f' %.05f {coin}' % size + COLOR_BLUE + ' for ~' + format_usd(size * coin_price) + ' USD'
                else:
                    msg += COLOR_GREEN + f'~%.05f {coin}' % (funds / coin_price) + COLOR_BLUE + ' with ' +  format_usd(funds) + ' USD'

                msg += COLOR_RESET + '\t' + format_usd(coin_price) + '/coin' + '  ' + cryptobot.analysis.format_seconds(time.time() - unixts) + ' ago'

                if portfolio:
                    msg += f'\t{COLOR_BLUE}--{COLOR_RESET} ' + format_usd(portfolio[1] + (portfolio[0] * coin_price)) + ' total value'

                msg += '\n'

            c.close()

            p = subprocess.Popen(['less', '-r', '-f', '+G', '/dev/stdin'], stdin=subprocess.PIPE)
            p.communicate(input=msg.encode('utf-8'))

        elif args.subparser in ['log', 'logs']:
            # XXX: make the path '/var/log/cryptobot.log' a config option
            p = subprocess.Popen(['less', '-r', '+F', '+G', '/var/log/cryptobot.log'])
            p.wait()

        elif args.subparser == 'analyze-market':
            logger.info('Performing market analysis as of %s (%d)...' % (str(datetime.datetime.now()), time.time()))
            cryptobot.analysis.analyze_market(test_run=args.force)
            logger.info('Done performing analysis. Run this command again in an hour or so.')

        elif args.subparser == 'check-price':
            #logger.info('Checking the coin\'s current price (as of %d) and storing in the database...' % time.time())
            # NOTE: dont use cache; it doesn't track which coin it's caching
            # XXX/HACK: this is pretty hacky
            if config.get('bot.coin') not in ['BTC', 'ETH']:
                coin_price = cryptobot.analysis.history.get_current_price(use_cache=False, commit=False)
                logger.info('Current configured coin price is %.2f USD / coin.' % coin_price)
            btc_price = cryptobot.analysis.history.get_current_price(use_cache=False, product_id_override='BTC-USD', commit=False)
            logger.info('Current BTC-USD price is %.2f USD / BTC.' % btc_price)
            eth_price = cryptobot.analysis.history.get_current_price(use_cache=False, product_id_override='ETH-USD')
            logger.info('Current ETH-USD price is %.2f USD / ETH.' % eth_price)
            # NOTE: the coin cache is corrupted at this point, don't do more logic!
            cryptobot.flash.check_flash(use_cache=False)

    except Exception as e:
        msg = 'Exception raised:\n' + ''.join(traceback.TracebackException.from_exception(e).format())
        logger.critical(msg)
        raise e
